package:
  name: memcached-exporter
  version: 0.11.2
  epoch: 0
  description: Exports metrics from memcached servers for consumption by Prometheus.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      
pipeline:
  - uses: go/install
    with:
      package: github.com/prometheus/memcached_exporter/cmd/memcached_exporter@v${{package.version}}
