package:
  name: memcached-exporter
  version: 0.11.2
  epoch: 0
  description: Exports metrics from memcached servers for consumption by Prometheus.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      
pipeline:
  # - uses: go/install
  #   with:
  #     package: github.com/prometheus/memcached_exporter/cmd/memcached_exporter@v${{package.version}}
  
  # fetch instead of go/install so that we can manually patch
  - uses: fetch
    with:
      uri: https://github.com/prometheus/memcached_exporter/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 360ac87b86e7ae704ea4db493bac1e1157a3c4f5cf57f24b9d66be24fb795e9f
  # TODO: remove this when it's fixed upstream
  - runs: |
      # Mitigate GHSA-hw7c-3rfg-p46j
      go get google.golang.org/protobuf@v1.29.1
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      go build -o ${{targets.destdir}}/usr/bin/memcached-exporter ./cmd/memcached_exporter
  - uses: strip